### ISSUE TITLE
Connect <LocalizedLink> with <AniLink> from gatsby-plugin-transition-link

### ISSUE THREAD

**Issue by cirocki** [openscript-ch/gatsby-plugin-i18n-l10n#113]
I found that problem and i have to choose, localized links or pretty transitions. There is a way to have both? :D

**Comment by gonzacaminos** [comment]
Hey @openscript, I can't use the Generic localized Link, what am I doing wrong?

I get a **Element type is invalid: expected a string (for built-in ' + 'components) or a class/function (for composite components) ' + ("but got: " + (type == null ? type : typeof type) + "." + info));
  28440 |         }**

```

import React from "react"
import { GenericLocalizedLink } from 'gatsby-plugin-i18n-l10n'
import AniLink from "gatsby-plugin-transition-link/AniLink"

export default function Button(props) {

  return(
    <div>
        <GenericLocalizedLink to="/imprint">
          {(args) => (
            <AniLink fade to={args.to}>
              Go to Page 4
            </AniLink>
          )}
        </GenericLocalizedLink>
    </div>
    
  )
}
```
