### ISSUE TITLE
Exclude pages for a given language

### ISSUE THREAD

**Issue by ctessier** [openscript-ch/gatsby-plugin-i18n-l10n#170]
Thank you for this plugin! 
I am testing things out but I cannot find the proper way to do what I need here. Thank you for your help.

**Is your feature request related to a problem? Please describe.**
I have pages that I don't want to generate for a given language.
I tried this way, but I get an error at build time:

```javascript
{
  locale: `af-ZA`,
  prefix: `af`,
  slugs: {
    '/page-1': '/bladsy-1',
    '/page-2': false, // also tried `''` but it just changes the URL
  },
  messages: afMessages,
}
```

The error I get is `TypeError: The "path" argument must be of type string. Received type boolean (
#0 5.155   false)`. 

In dev mode, Gatsby doesn't seem to complain though. **And the plugin responds well because it then hides the locale in the language switcher when on this page.**

**Describe the solution you'd like**
It would be great if setting a path to `false` in a language would result in the page not being generated for this locale.

**Additional context**
![image](https://github.com/openscript-ch/gatsby-plugin-i18n-l10n/assets/4518186/4517ebaf-648e-4063-9f79-bd692674ba85)

**Comment by openscript** [comment]
Thank you for using this plugin and raising the request. I've added a new option `pageBlacklist`, which lets you prevent the creation of pages for given paths and languages.

```
      {
        locale: `de-CH`,
        prefix: `de`,
        slugs: {
          '/products': '/produkte',
          '/products#donut-filled-with-jam': '/produkte#berliner',
          '/services/software-development': '/dienstleistungen/softwareentwicklung'
        },
        pageBlacklist: ['/do-not-translate-to-german'], // If there is a page with the a given path it won't be translated
        messages: {
          "language": "Deutsch"
        },
        ```

I'm happy to hear, if this works out for you! Cheers

**Comment by ctessier** [comment]
Thank you very much @openscript ! Sounds perfect!
I'll try that out when I get some time and will let you know 😃
