### ISSUE TITLE
Gatsby option `trailingSlash`  not considered

### ISSUE THREAD

**Issue by acocheo** [openscript-ch/gatsby-plugin-i18n-l10n#176]
By now this plugin doesn't use Gatsby [`trailingSlash`](https://www.gatsbyjs.com/docs/reference/config-files/gatsby-config/#trailingslash) option for URLs.
Every time the plugin needs to build a path from scratch, it calls `trimRightSlash`. For example [here](https://github.com/openscript-ch/gatsby-plugin-i18n-l10n/blob/464c967523e4bdda6de79ab1eb0fd58767cf59e7/src/onCreateNode/translateNode.ts#L172)  
Example
```
/test/ ✅   ==>    /test ❌
```
(**Note**: Gatsby automatically does a redirect to correct url, but wrong urls give troubles to SEO).  
  
Consider that trailingSlash default is *always*.

**Comment by acocheo** [comment]
This bug impacts every times the code uses the `translations` context. For example:
- creation of `hrefLang` tags [here](https://github.com/openscript-ch/gatsby-plugin-i18n-l10n/blob/4f5109f3ab5f391a7909ed9e8c950f5caa387745/src/onRenderBody.tsx#L23)
- Language switcher [here](https://github.com/openscript-ch/gatsby-plugin-i18n-l10n/blob/4f5109f3ab5f391a7909ed9e8c950f5caa387745/src/components/LanguageSwitcher.tsx#L15)

**Comment by openscript** [comment]
Thank you for creating this issue.

I'll try to observe https://www.gatsbyjs.com/docs/reference/config-files/gatsby-config/#trailingslash and do it as configured for Gatsby.

**Comment by openscript** [comment]
Unfortunately there is no possibility to read the option from a plugin. I've introduced another option here: https://github.com/openscript-ch/gatsby-plugin-i18n-l10n/pull/187

Does this work for you?

**Comment by acocheo** [comment]
Branch downloaded, compiled and tested in a project.
It seems ok! All urls I can see (in hrefLang etc ) are correct
TY! 
Waiting for release

**Comment by openscript** [comment]
I've released a new version. I hope everything works out. Thank you for raising this.

**Comment by acocheo** [comment]
Hi again @openscript ,
sorry but we have noticed an issue during production build.
It's about 404 page

```
 ERROR  UNKNOWN

Truncated page data information for the failed page "/it/404.html/": {
  "errors": {},
  "path": "/it/404.html/",
  "slicesMap": {},
  "pageContext": {
    "locale": "it-IT",
    "localePagesId": "404.html",
    "translations": [
      {
        "locale": "en-GB",
        "path": "/404.html/"
      }
    ],
    "prefix": "it"
  }
}

failed Building static HTML for pages - 2.622s
```
Reading docs
https://www.gatsbyjs.com/docs/how-to/adding-common-features/add-404-page/
I see that the 404 page is compiled as  `404.html`, so I think it's a special route where trailingSlash should not be used
(my guess)

Thanks for your help
