### ISSUE TITLE
hreflang meta tag is wrong

### ISSUE THREAD

**Issue by DDaehn** [openscript-ch/gatsby-plugin-i18n-l10n#186]
On all sites the hreflang tags are always like this:

`
<link rel="alternate" hreflang="x-default" hreflang="https://www.website.com/">
<link rel="alternate" hreflang="de" hreflang="https://www.website.com/de">
<link rel="alternate" hreflang="en" hreflang="https://www.website.com/">
`

It does not generate paths for subpages. Also it does not add the trailing slash which is problematic for SEO.

In that context it also would be great to have the possibility to disable the meta tag generation, because we also use gatsby-plugin-next-seo for seo context, so the meta tags are doubled.

**Comment by openscript** [comment]
Hi @DDaehn 

I think something is off with your configuration or how you use the plugin.

There are automatic tests covering the generation of meta tags here: https://github.com/openscript-ch/gatsby-plugin-i18n-l10n/blob/main/src/onRenderBody.test.tsx#L54

For the trailing slash issue, I've created a PR here https://github.com/openscript-ch/gatsby-plugin-i18n-l10n/pull/187. Please try it out and tell me if it works for you.
