### ISSUE TITLE
No trailing slash for 404 pages

### ISSUE THREAD

**Issue by openscript** [openscript-ch/gatsby-plugin-i18n-l10n#189]
Hi again @openscript ,
sorry but we have noticed an issue during production build.
It's about 404 page

```
 ERROR  UNKNOWN

Truncated page data information for the failed page "/it/404.html/": {
  "errors": {},
  "path": "/it/404.html/",
  "slicesMap": {},
  "pageContext": {
    "locale": "it-IT",
    "localePagesId": "404.html",
    "translations": [
      {
        "locale": "en-GB",
        "path": "/404.html/"
      }
    ],
    "prefix": "it"
  }
}

failed Building static HTML for pages - 2.622s
```
Reading docs
https://www.gatsbyjs.com/docs/how-to/adding-common-features/add-404-page/
I see that the 404 page is compiled as  `404.html`, so I think it's a special route where trailingSlash should not be used
(my guess)

Thanks for your help

_Originally posted by @acocheo in https://github.com/openscript-ch/gatsby-plugin-i18n-l10n/issues/176#issuecomment-1921105990_

**Comment by openscript** [comment]
How the fix works for you @acocheo.

**Comment by acocheo** [comment]
Tested today.
Flawless. GG
🙏
