### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by alesma** [openscript-ch/gatsby-plugin-i18n-l10n#34]
Hey,

I have noticed this plugin uses a lookbehind in a regexp which is not supported by [Safari](https://caniuse.com/js-regexp-lookbehind)

[https://github.com/openscript-ch/gatsby-plugin-i18n-l10n/blob/main/src/utils/path.ts#L30](https://github.com/openscript-ch/gatsby-plugin-i18n-l10n/blob/main/src/utils/path.ts#L30)

Not sure if is a choice or if you would accept a PR to address it.

**Comment by openscript** [comment]
Hi @alesma 

In my opinion this should be fine, because the regular expression is executed by node during server side generation (SSG). What do you think?

**Comment by alesma** [comment]
it is also executed in the browser, from my understanding after hydration.

I was checking your site on safari and I see the same issue I have on mine

![image](https://user-images.githubusercontent.com/465943/176785921-85e5071e-ccb2-48f9-97ef-bda09940767d.png)

**Comment by openscript** [comment]
You are right. `LocalizedLink` needs something from `path.ts` and with that this regular expression. It is never evaluated, but the browsers seem to prepare the regular expression in case in needs to be executed.

![image](https://user-images.githubusercontent.com/1105080/176991826-30b7f3eb-23d5-4ce3-badd-ebe2fff77c0c.png)

**Comment by openscript** [comment]
Thank you for reporting.
