### ISSUE TITLE
Issues when setting wrapWithLayout

### ISSUE THREAD

**Issue by alesma** [openscript-ch/gatsby-plugin-i18n-l10n#47]
When using this plugin and wrapping the pages in a layout using Gatsby wrapWithLayout, the component exported is not wrapped inside `<IntlProvider>`.

resulting in 

![image](https://user-images.githubusercontent.com/465943/178941054-46567328-2720-4fee-8517-72942d1925e2.png)

I believe the problem is that the plugin should rather use wrapRootElement instead of wrapPageElement as according to Gatsby docs 

This is useful to set up any Provider components that will wrap your application. For setting persistent UI elements around pages use [wrapPageElement](https://www.gatsbyjs.com/docs/reference/config-files/gatsby-ssr/#wrapPageElement).

I have seen this issue also on other plugins tbh, not sure if there is any limitation to use the suggested function

**Comment by alesma** [comment]
my bad I meant to write wrapPageElement.

so currently the plugin is using wrapPageElement to add the providers, instead gatsby suggests to use wrapRootElement and keep wrapPageElement for UI

**Comment by alesma** [comment]
I think the same issue is also on https://www.gatsbyjs.com/plugins/gatsby-plugin-react-i18next/ and I found an article about a workaround for that particular plugin https://andremonteiro.pt/gatsby-i18next-wrap-page-element/

**Comment by openscript** [comment]
Do you have your own react-intl provider somewhere?

**Comment by openscript** [comment]
I  cannot reproduce the problem, but I'm more than happy to help as soon as I can :)

**Comment by armandoborge** [comment]
I solved this same issue using the snippet below on gatsby-browser.js

```
export const wrapPageElement = ({ element, props }) => {
    return (
        <IntlProvider locale={navigator.language}>
            <Layout {...props}>{element}</Layout>
        </IntlProvider>
    )
}
```

**Comment by openscript** [comment]
Actually the plugin should inject this:

https://github.com/openscript-ch/gatsby-plugin-i18n-l10n/blob/main/src/wrapPageElement.tsx
with
https://github.com/openscript-ch/gatsby-plugin-i18n-l10n/blob/main/gatsby-ssr.ts

On which version of Gatsby are you? @armandoborge

**Comment by armandoborge** [comment]
It is a private repository.
The issue occurs if the **gatsby-browser.js** file contains an export **wrapPageElement**, in my case, I am using this function export to wrap all my pages inside a layout component. As soon as I remove my function the error disappears.

It seems the custom declaration overwrites the one created by the plugin.
